### PR TITLE
Modernize JSON::RPC 

### PR DESCRIPTION
**Pull request by azawawi**
- Modernize META.info to META6.json
- Add Test::META tests
- CI: Test on macOS and windows on 2016.12 and latest. Please enable AppVeyor support.
- Add missing LICENSE file.

### CODE REVIEW

**Comment by bbkr** [comment]
Thanks, I'll review your changes during weekend (not much free time after $dayjob).

If we speak about modernization - this module was written in early Parrot VM era. It is full of antipatterns (exception based flow control, procedural design without proper requests isolation). And it is pretty much dead protocol - https://www.google.com/trends/explore?q=json-rpc,http%20rest .

I have to estimate time required for proper refactoring (with support of parallel batch processing of course and switch to more polished modules like JSON::Fast) and decide what will be the future of this module.

**Comment by azawawi** [comment]
@bbkr  Thanks for your time. I am using it for [Odoo::Client](https://github.com/azawawi/perl6-odoo-client) so it is not dead as a protocol considering an big enterprise Odoo ERP is using it :)

**Comment by bbkr** [comment]
Please take a look at refactoring roadmap https://github.com/bbkr/jsonrpc/issues/32 .
Comments are welcome.

I think this should take about 2-3 weeks, including applying changes from your MR and enabling AppVeyor.

**Comment by azawawi** [comment]
Updated the roadmap. Thanks for your work 👍

**Comment by azawawi** [comment]
Thanks 👍

**Pull request merged**
